### ISSUE TITLE
NN Ideas

### ISSUE THREAD

**Issue by arlyon** [dragorhast/submission#21]
### Net Neutrality protects innovation

- Internet is the foundation of modern innovation
- every piece of technology is running on a stack of open software that has been built collaboratively using the internet as a medium for massive, distributed, development
- imagine if, when the first developers started building and releasing the software that surrounds us today (gnu, openssl, gcc, linux kernel, mysql, apache) a tech giant (IBM, Oracle, Microsoft, Xerox) decided that they wanted to limit access to these projects? without net neutrality there is no legal recourse
- without protections over the fundamental infrastructure for our careers (all software, not just FOSS) there is nothing stopping a large bad actor from completely crippling anything they see fit
- larger barrier to entry for small disruptive companies
- in a world where globalism, fueled directly by the internet, is so crucial, this cannot be allowed

### Bandwidth throttling

todo: slow your network down

https://en.wikipedia.org/wiki/Bandwidth_throttling

### Capping Data

todo: limit your data

https://en.wikipedia.org/wiki/Data_cap

### Deep packet inspection

Enables eavesdropping and censorship. This (combined with Theresa May's attempts to scrap the EU human rights act, and encryption) is a slippery slope.

- surveillance creep. what is not okay today may be mundane tomorrow
- completely invisible

http://fuchs.uti.at/wp-content/uploads/DPI.pdf

> Parsons warns that with the help of DPI it is “possible to construct vast social net‐work maps” (Parsons 2008, 12) because the technology allows to identify the source and destination (e.g. email‐addresses or user names on social media like Facebook or Twitter) as well as the content of each online communication. Bendrath and Mueller (2012, 1148) make an analogy between an ISP and a postal worker in order to show how DPI can potentially result in privacy violations: “Now imagine a postal worker who [...] * Opens up all packets and letters; * Reads the content; * Checks it against databases of illegal material and when finding a match sends a copy to the police authorities; * Destroys letters with prohibited or immoral content; * Sends packages for its own mail‐order services to a very fast delivery truck, while the ones from competitors go to a slow, cheap sub‐contractor. Imagine also that the postal worker could do this without delaying or damaging the packets and letters compared to his (former, now fired) daydreaming colleague. This is what DPI technology is capable of. [...] Such a postal system [...] invades the privacy of communications and introduces opportunities for regulation and censorship whole increasing the feasibility of imposing intermediary responsibility on IPSs”. 

https://en.wikipedia.org/wiki/Deep_packet_inspection

### Packaged internet / tiered service

The great strength of the internet is the ability to see and do anything without restriction. Within the scope of the law, no other entity is able to govern your choices. This may change. For years, sky has been collecting data to extract as much money as possible from its subscribers. By deliberately splitting channels into highly specific packages, they have optimized their offerings for revenue. If you

- like listening to music
- like streaming video
- enjoy social media
- want to play computer games
- reading liberal news
- reading conservative news

your data will be categorized and you will be billed for it.

https://en.wikipedia.org/wiki/Tiered_Internet_service

### Zero Rating

Allowing unlimited access to some parts of the internet but not others.

- https://www.voxi.co.uk/benefits
- https://ee.co.uk/why-ee/apple-music

### Paid Peering

The ISP also charges the companies you use to get access to you. Double dipping. Who do you think takes on these costs? Netflix isn't just going to cancel one of their shows to make up the difference.

### You lose money

- tiered service designed to charge you more
- charging a premium during "peak hours"
- fast-lane vs slow-lane: you will need to pay more to prevent artificial bandwidth throttling
- you may need to pay for expensive data caps, or be put on a metered connection (bye bye steam)
- you are at the mercy of your ISP (imagine being "at the mercy" of your water supplier!)
- ISPs can bill you to access the internet, and bill the internet to access you. 

https://www.theverge.com/2014/2/23/5439566/the-wall-street-journal-confirms-multiyear-traffic-deal-between

### You lose (more of) your private data

Are you comfortable with a private company inspecting every packet you send? With the massive influx of data breaches happening do you feel safe letting these companies store it? This is what happens with Zero Rating and while nice for the users, it is damaging for the economy.

ISPs are incentivized to reduce your anonymity. VPNs limit their ability to categorize your data and so they will attempt to limit (or ban) VPNs. ISPs have financial incentive to de-anonymize you as much as possible such that they may most accurately categorize your data and bill you for it. Not to mention your entire browsing history may be available to purchase:

https://www.theverge.com/2017/3/28/15080436/us-house-votes-to-let-isps-share-web-browsing-history

And, to top it off, you have no way of gauging how much of your data is actually being collected. 

### You lose access to content

Disney, Amazon, Netflix, Hulu, HBO, Spotify, Apple Music, Tidal, Deezer, Google Music

Every company is bringing out their own streaming platform, and great innovation is happening. You are free to choose which one you want, but each service, in an attempt to gain market share, is restricting their licensing. If you want HBO shows, you need HBO. Piracy is going up, but that is only tangentially related.

Imagine this applied to your local ISP. They launch their own streaming platform, but bill you if you use the others. 

- ISPs throttling services to promote their own: https://arstechnica.com/tech-policy/2017/12/att-says-it-never-blocked-apps-fails-to-mention-how-it-blocked-facetime/ 
- Making companies pay more to access data. 
- New competitors in the space are automatically at a disadvantage for something they cannot control.

### You lose your access to information

You would assume that what you search for online is impartial and unbiased. Google has caught flak in the past for biased search results (simply, people get served what they want to see) leading to dangerous confirmation bias and polarization.

This is before there is a malicious actor deliberately controlling what you see. It is not unreasonable to think that without treating internet as a first class citizen that an ISP or government could limit or "shape" your view of the world

https://en.wikipedia.org/wiki/Search_neutrality

### You lose your browser. Injected, targeted ads, and the end of ad blockers.

Your data is not your own. While google knows most things you do, your ISP knows everything. Your ISP can change your perspective of the internet. Ads is the first step. What stops someone from paying your service provider to hide (or promote) a scathing article?

You (probably) have an ad blocker enabled. It currently works by a combination of DOM node filtering and host blacklisting. If your ads are served (read injected without consent) directly by your ISP, you have little to no recourse.

### Stifling innovation

- Startups will struggle to compete, unable to afford paid peering and raising barrier to entry.
- Startups may be placed on a slower line by default
- Startups will have to deal with more complex plans

### This fucking guy

He looks like a total wanker.

![image](https://user-images.githubusercontent.com/8715352/51347041-123ecc00-1a97-11e9-808a-bca964e7269b.png)

**Comment by scain40** [comment]
Source: https://ncac.org/resource/network-neutrality-and-the-fight-to-save-the-internet-background
