### ISSUE TITLE
Final Usability Evaluation [20 marks]

### ISSUE THREAD

**Issue by arlyon** [dragorhast/submission#26]
> Perform a final usability evaluation of your product, similar to the one you conducted in Stage 1 but using the full system. Again try to get 6-8 participants for this study and think of tasks that make use of the full set of features you have implemented. Try to collect both subjective data (e.g., what the user thinks/says) and o bjective measures (e.g., number of successful tasks, time to completion). This evaluation is separate from the Expo, where you will be showing off the product, not collecting data.

### Things Left To Do

- [ ] Adapt the previous study
- [ ] Collect data on 6 people
- [ ] Analyse it

**Comment by vanillafritz** [comment]
Here is the link for the usability survey for stage 3:

https://docs.google.com/forms/d/1b6nG0aLR2DMAoFvt8RgM-Q2mVRyW6sUuEKvQxt9i4kY/edit?usp=sharing

**Comment by vanillafritz** [comment]
> > Perform a final usability evaluation of your product, similar to the one you conducted in Stage 1 but using the full system. Again try to get 6-8 participants for this study and think of tasks that make use of the full set of features you have implemented. Try to collect both subjective data (e.g., what the user thinks/says) and objective measures (e.g., number of successful tasks, time to completion). This evaluation is separate from the Expo, where you will be showing off the product, not collecting data.
> 
> ### Things Left To Do
> * [X]  Adapt the previous study
> * [x]  Collect data on 6 people
> * [ ]  Analyse it

**Comment by vanillafritz** [comment]
Here is the usability study data with some basic comments.

https://docs.google.com/document/d/15DTS87U9tWHzz3RRkVB_auSlUSCbM-lwqzECymhWzAc/edit?usp=sharing
