### ISSUE TITLE
Design Specification

### ISSUE THREAD

**Issue by arlyon** [dragorhast/submission#8]
## Design

- [x] functional requirements
- [x] non-functional requirements
- [ ] UML diagrams
- [ ] use cases

**Comment by arlyon** [comment]
## Non-Functional Requirements

| S |Speed of the software	
| S |Software should be working 24/7	
| S |Software will be using Python for app	
| S |Security (Privacy policies)
| S |Software should be working correctly	
| S |Both must have accessibility options 	
| S |Usability of both user/admin side

**Comment by arlyon** [comment]
## Boundaries

- We will not develop the app for hardware such as smart watches	
- We will only allow for bike bookings

**Comment by arlyon** [comment]
graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;

**Comment by borebos** [comment]
Google docs for Use cases: 

https://docs.google.com/document/d/1FEpGF-9ojwk68q6CoazzZaaK06ab4AOM96GpBlvs5p8/edit?usp=sharing

**Comment by arlyon** [comment]
I was looking through the slides for the individual report
