### ISSUE TITLE
Next Meeting

### ISSUE THREAD

**Issue by arlyon** [dragorhast/submission#9]
- [x] review code of conduct
- [x] talk about [TDD](https://en.wikipedia.org/wiki/Test-driven_development) for technical correctness, [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development) for behavioral correctness

**Comment by borebos** [comment]
Agreeing on the way the system works:
- [ ] What method is going to be used for picking up the bike
- [ ] How is the report issue actually work on the app
- [ ] How does admin operate the app for reports? 
- [ ] Linking to terminology, how are we referring to each part of the system?
